Admin_app/urls.py
from django.urls import path
from admin_app.views import *
from django.conf import settings
from django.conf.urls.static import static
app_name = 'admin_app'
urlpatterns = [
    # ----Category----

    path(route='category_register/',
         view=category_register_view, name="category_register"),
    path(route='category_list/', view=category_list_view, name="category_list"),
    path(route='category_update/<int:pk>/',
         view=category_update_view, name="category_update"),
    path(route='category_delete/<int:pk>/',
         view=category_delete_view, name="category_delete"),

    # ----PRODUCT----
    path(route='p_register/', view=item_register_view, name="p_register"),
    path(route='p_list/', view=item_list_view, name="p_list"),
    path(route='p_details/', view=item_details_view, name="p_details"),
    path(route='p_update/<int:pk>/', view=item_update_view, name="p_update"),
    path(route='p_delete/<int:pk>/', view=item_delete_view, name="p_delete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL,
    #   document_root=settings.STATIC_ROOT)

Grocery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Grocery.views import home_view

urlpatterns = [
    path('Admin/', admin.site.urls),
    path(route='customer_app/',
         view=include('customer_app.urls'), name='customer_app'),
    path(route='admin_app/', view=include('admin_app.urls'), name='admin_app'),
    path(route='cart/', view=include('cart.urls'), name='cart'),
    path(route='buy_app/', view=include('buy_app.urls'), name='buy_app'),
    path(route='', view=home_view, name='home_view'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL,
    #   document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from cart.views import cart_view,cart_register,cart_remove

app_name='cart_app'
urlpatterns=[
    path(route='cart_list/',view=cart_view,name='cart_list'),
    path(route='cart_register/<int:p_id>/<int:cust_id>/<str:iname>/<iprice>/',view=cart_register,name='cart_register'),
    path(route='cart_remove/<int:cart_id>/',view=cart_remove,name='cart_remove'),
]

Admin_app/models.py
from django.db import models
from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile

# Create your models here.


class category_items(models.Model):
    cat_id = models.AutoField(primary_key=True)
    cat_name = models.CharField(max_length=50)
    cat_img = models.ImageField(upload_to='category/')

    def __str__(self):
        return self.cat_name


class product_item(models.Model):
    cat_id = models.ForeignKey(category_items, on_delete=models.CASCADE)
    item_id = models.AutoField(primary_key=True)
    item_name = models.CharField(max_length=50)
    item_desc = models.TextField()
    item_quantity = models.PositiveIntegerField()
    price = models.FloatField()
    img = models.ImageField(upload_to='items/')

    def __str__(self):
        return self.item_name

    def save(self, *args, **kwargs):
        if self.img:
            # Open the uploaded image
            img = Image.open(self.img)

            # Set the new resolution
            new_width = 500
            new_height = 500
            resized_img = img.resize((new_width, new_height), Image.LANCZOS)

            # Save the resized image back to the model's image field
            buffer = BytesIO()
            resized_img.save(buffer, format='JPEG')  # Change format as needed
            self.img.save(self.img.name, ContentFile(
                buffer.getvalue()), save=False)
        super(product_item, self).save(*args, **kwargs)

Admin_app/forms.py
from typing import Any
from django import forms
from admin_app.models import product_item, category_items
from PIL import Image


def change_resolution(input_image_path, output_image_path, new_width=500, new_height=500):
    # Open the image
    image = Image.open(input_image_path)

    # Resize the image
    resized_image = image.resize((new_width, new_height), Image.LANCZOS)

    # Save the resized image
    resized_image.save(output_image_path)


class category_form(forms.ModelForm):
    class Meta:
        model = category_items
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['Job_role'].widget.attrs.update(
        #     {"rows": "4", "cols": "50"})
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control border-2 border-secondary w-75 py-2 px-4 rounded-pill'
            field.widget.attrs['placeholder'] = "Enter "+str(field.label)


class product_form(forms.ModelForm):
    class Meta:
        model = product_item
        fields = "__all__"
        widgets = {'item_desc': forms.Textarea(
            attrs={"rows": "4", "cols": "50"})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print(self.fields)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control border-2 border-secondary w-75 py-2 px-4 rounded-pill'
            field.widget.attrs['placeholder'] = "Enter "+str(field.label)

Admin_app/views.py
from django.shortcuts import render, redirect
from admin_app.models import category_items, product_item
from admin_app.forms import product_form, category_form
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.

#   ============ CATEGORY Register, List, Update, Delete


def category_register_view(request):
    form = category_form()
    if request.method == 'POST' and request.FILES:
        form = category_form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Category is added.")
        else:
            messages.error(request, "Category is not added.")
    return render(request=request, template_name='category_register.html', context={'form': form})


def category_list_view(request):
    res = category_items.objects.all()
    return render(request=request, template_name='category_list.html', context={'data': res})


def category_update_view(request, pk):
    res = category_items.objects.get(cat_id=pk)
    form = category_form(instance=res)
    if request.method == 'POST' or request.FILES:
        res = category_items.objects.get(cat_id=pk)
        form = category_form(request.POST, request.FILES, instance=res)
        if form.is_valid():
            form.save()
            messages.success(request, "Category is Updated.")
        else:
            messages.error(request, "Category is not Updated.")
    return render(request=request, template_name='category_update.html', context={'data': form, 'res': res})


def category_delete_view(request, pk):
    res = category_items.objects.get(cat_id=pk)
    if request.method == 'POST':
        if category_items.objects.get(cat_id=pk).delete():
            messages.success(request, "Category Deleted")
        else:
            messages.error(request, "Category is not Deleted")
        return redirect('/admin_app/category_list')
    return render(request=request, template_name='category_delete.html', context={'data': res})


#   ============ (item) PRODUCT Register, List, Update, Delete
def item_register_view(request):
    form = product_form()
    if request.method == 'POST' and request.FILES:
        form = product_form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Product added")
        else:
            messages.error(request, "Product is not added")
        return redirect('/admin_app/p_list/')
    return render(request=request, template_name='item_register.html', context={'form': form})


def item_list_view(request):
    category = category_items.objects.all()
    res = product_item.objects.all()
    return render(request=request, template_name='item_list.html', context={'data': res, 'category': category})


def item_details_view(request):
    if request.method == 'POST':
        res = product_item.objects.filter(cat_id=request.POST['cat_list'])
    return render(request=request, template_name='item_list.html', context={'data': res})


def item_update_view(request, pk):
    res = product_item.objects.get(item_id=pk)
    form = product_form(instance=res)
    if request.method == "POST":
        res = product_item.objects.get(item_id=pk)
        form = product_form(request.POST, request.FILES, instance=res)
        if form.is_valid():
            form.save()
            messages.success(request, "Product Updated")
        else:
            messages.error(request, "Product is not Updated")
        return redirect('/admin_app/p_list')
    return render(request=request, template_name='item_update.html', context={'form': form, 'res': res})


def item_delete_view(request, pk):
    res = product_item.objects.get(item_id=pk)
    if request.method == 'POST':
        if product_item.objects.get(item_id=pk).delete():
            messages.success(request, "Product Deleted")
        else:
            messages.error(request, "Product is not deleted")
        return redirect('/admin_app/p_list')
    return render(request=request, template_name='item_delete.html', context={'data': res})

Admin_app/templates/category_delete.html
{% extends "admin_home.html" %}
{% load static %}
{% block model %}
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-center">
            </div>
        </div>
    </div>
</div>
{% endblock model %}


{% block hero %}


<div class="container-fluid py-5 mb-5 hero-header">
    <div class="container py-5">
        <div class="row g-5 align-items-center">
            <div class="col-md-12 col-lg-7">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <h5 class="mb-5 display-3 text-primary">Category Delete</h5>
                    <h3>Are you sure to delete record id: {{data.cat_id}}</h3>
                    <h3>Category Name:{{data.cat_name}}</h3>
                    <div class="position-relative mx-auto">
                        <button type="submit"
                            class="btn btn-primary border-2 border-secondary py-3 px-4 position-absolute rounded-pill text-white h-60"
                            style="top: 0; right: 25%;">Delete Category</button>
                    </div>
                </form>
            </div>
            <div class="col-md-12 col-lg-5">
                <div id="carouselId" class="carousel slide position-relative" data-bs-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active rounded">
                            <img src="{{ data.cat_img.url}}" alt="Current Image" width="50" height="50"
                                class="img-fluid w-100 h-100 bg-secondary rounded" alt="First slide">
                        </div>
                    </div>
                </div>
                <h3>List of Categories and Products:</h3>
                <a href="{% url 'admin_app:category_list' %}"><button
                        class="btn btn-primary border-2 border-secondary">Category List</button></a>
                <a href="{% url 'admin_app:p_register' %}"><button class="btn btn-primary border-2 border-secondary">Add
                        Product</button></a>
                <a href="{% url 'admin_app:p_list' %}"><button class="btn btn-primary border-2 border-secondary">Product
                        List</button></a>
            </div>
        </div>
    </div>
</div>
{% endblock hero%}

{% block featurs %}
{% endblock featurs%}

{% block fruits %}
{% endblock fruits %}


{% block featur-2 %}

{% endblock featur-2 %}

{% block vesitable %}

{% endblock vesitable %}

{% block banner %}

{% endblock banner %}

{% block Bestsaler %}

{% endblock Bestsaler %}


{% block testimonial %}

{% endblock testimonial %}

{% block button %}
{% endblock %}

{% block foot %}
{% endblock %}

{% block offer %}
{% endblock %}

{% block footer_tag %}
{% endblock %}

Admin_app/templates/category_list.html
{% extends "admin_home.html" %}
{% load static %}
{% block model %}
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-center">
                <div class="input-group w-75 mx-auto d-flex">
                    <input type="search" class="form-control p-3" placeholder="keywords"
                        aria-describedby="search-icon-1">
                    <span id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock model %}


{% block hero %}
<div class="container-fluid py-5 mb-5 hero-header">
    <div class="container py-5">
        <div class="row g-5 align-items-center">
        </div>
    </div>
</div>
{% endblock hero%}

{% block featurs %}
{% endblock featurs%}

{% block fruits %}
{% endblock fruits %}


{% block featur-2 %}

{% endblock featur-2 %}

{% block vesitable %}

{% endblock vesitable %}

{% block banner %}

{% endblock banner %}

{% block Bestsaler %}
<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="text-center mx-auto mb-5" style="max-width: 700px;">
            <h1 class="display-4"> All Categories</h1>
        </div>
        <div class="row g-4">
            {% if data %}
            {% for i in data%}
            <div class="card-4 col-lg-6 col-xl-4" style="max-width: 30rem;">
                <div class="p-4 rounded bg-light">
                    <div class="row align-items-center">
                        <a href="#" class="h5">{{i.cat_name|title}}</a><br>
                        <div class="col-6">
                            <div class="d-flex justify-content-center align-items-center"
                                style="width: 150px; height: 150px; border: 1px solid; border-radius: 50%; background-image: url({{i.cat_img.url}}); background-position: center; background-repeat: no-repeat; background-size: auto;">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="d-flex my-3">
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star"></i>
                            </div>
                            <a href="{% url 'admin_app:category_update' pk=i.cat_id %}"
                                class="btn border border-secondary rounded-pill px-3 text-primary"><i
                                    class="fa fa-edit me-2 text-primary"></i> Update </a>
                            <hr>
                            <a href="{% url 'admin_app:category_delete' pk=i.cat_id%}"
                                class="btn border border-secondary rounded-pill px-3 text-primary"><i
                                    class="fa fa-trash me-2 text-primary "></i> Delete</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <h3>List of Categories and Products:</h3>
        <a href="{% url 'admin_app:category_register' %}"><button
                class="btn btn-primary border-2 border-secondary">Category
                Register</button></a>
        <a href="{% url 'admin_app:p_register' %}"><button class="btn btn-primary border-2 border-secondary">Add
                Product</button></a>
        <a href="{% url 'admin_app:p_list' %}"><button class="btn btn-primary border-2 border-secondary">Product
                List</button></a>
    </div>
</div>

{% endblock Bestsaler %}


{% block testimonial %}

{% endblock testimonial %}

{% block button %}
{% endblock %}

{% block foot %}
{% endblock %}

{% block offer %}
{% endblock %}

{% block footer_tag %}
{% endblock %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Category List</title>
</head>

<body>
    {% for i in messages %}
    <h2>{{i}}</h2>
    {% endfor %}

    <div>
        {% if data %}
        <table border="2px solid">
            <tr>
                <th>id</th>
                <th>name</th>
                <th>Image</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
            {% for i in data %}
            <tr>
                <td>{{i.cat_id}}</td>
                <td>{{i.cat_name}}</td>

                <td>{% if i.cat_img %}<img src="{{ i.cat_img.url }}" height="75" width="75">{% endif %}</td>
                <td><a href=" {% url 'admin_app:category_update' pk=i.cat_id %}"><button>Update</button></a></td>
                <td><a href="{% url 'admin_app:category_delete' pk=i.cat_id %}"><button>Delete</button></a></td>

            </tr>
            {% endfor %}
        </table>
        {% else %}
        <h2>Data is not found</h2>
        {% endif %}
    </div><br>

    <div>
        <a href="{% url 'admin_app:category_register' %}"><button>To Add Category</button></a>
        <a href="{% url 'admin_app:p_register' %}"><button>To Add Product</button></a>
    </div>

</body>

</html>

Admin_app/templates/category_register.html
{% extends "admin_home.html" %}
{% load static %}
{% block model %}
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-center">
                <div class="input-group w-75 mx-auto d-flex">
                    <input type="search" class="form-control p-3" placeholder="keywords"
                        aria-describedby="search-icon-1">
                    <span id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock model %}


{% block hero %}


<div class="container-fluid py-5 mb-5 hero-header">
    <div class="container py-5">
        <div class="row g-5 align-items-center">
            <div class="col-md-12 col-lg-7">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1 class="mb-5 display-3 text-primary">Category Register</h1>
                    <div class="position-relative mx-auto">
                        <table>
                            {{form}}
                        </table>
                        <button type="submit"
                            class="btn btn-primary border-2 border-secondary py-3 px-4 position-absolute rounded-pill text-white h-60"
                            style="top: 0; right: 25%;">Add Category</button>
                    </div>
                </form>
            </div>
            <div class="col-md-12 col-lg-5">
                <div id="carouselId" class="carousel slide position-relative" data-bs-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active rounded">
                            <img src="{% static 'img/hero-img-1.png' %}"
                                class="img-fluid w-100 h-100 bg-secondary rounded" alt="First slide">
                            <a href="#" class="btn px-4 py-2 text-white rounded">Fruites</a>
                        </div>
                        <div class="carousel-item rounded">
                            <img src="{% static 'img/hero-img-2.jpg' %}" class="img-fluid w-100 h-100 rounded"
                                alt="Second slide">
                            <a href="#" class="btn px-4 py-2 text-white rounded">Vesitables</a>
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselId"
                        data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselId"
                        data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
                <h3>List of Categories and Products:</h3>
                <a href="{% url 'admin_app:category_list' %}"><button
                        class="btn btn-primary border-2 border-secondary">Category
                        List</button></a>
                <a href="{% url 'admin_app:p_register' %}"><button class="btn btn-primary border-2 border-secondary">Add
                        Product</button></a>
                <a href="{% url 'admin_app:p_list' %}"><button class="btn btn-primary border-2 border-secondary">Product
                        List</button></a>
            </div>
        </div>
    </div>
</div>
{% endblock hero%}

{% block featurs %}
{% endblock featurs%}

{% block fruits %}
{% endblock fruits %}


{% block featur-2 %}

{% endblock featur-2 %}

{% block vesitable %}

{% endblock vesitable %}

{% block banner %}

{% endblock banner %}

{% block Bestsaler %}

{% endblock Bestsaler %}


{% block testimonial %}

{% endblock testimonial %}

{% block button %}
{% endblock %}

{% block foot %}
{% endblock %}

{% block offer %}
{% endblock %}

{% block footer_tag %}
{% endblock %}

Admin_app/templates/category_update.html
{% extends "admin_home.html" %}
{% load static %}
{% block model %}
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-center">
                <div class="input-group w-75 mx-auto d-flex">
                    <input type="search" class="form-control p-3" placeholder="keywords"
                        aria-describedby="search-icon-1">
                    <span id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock model %}


{% block hero %}


<div class="container-fluid py-5 mb-5 hero-header">
    <div class="container py-5">
        <div class="row g-5 align-items-center">
            <div class="col-md-12 col-lg-7">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h4 class="mb-5 display-3 text-primary">Category Update</h4>
                    <div class="position-relative mx-auto">
                        <table>
                            {{data}}
                        </table>
                        <button type="submit"
                            class="btn btn-primary border-2 border-secondary py-3 px-4 position-absolute rounded-pill text-white h-60"
                            style="top: 0; right: 25%;">update Category</button>
                    </div>
                </form>
            </div>
            <div class="col-md-12 col-lg-5">
                <div id="carouselId" class="carousel slide position-relative" data-bs-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active rounded">
                            <img src="{{ res.cat_img.url}}" alt="Current Image" width="50" height="50"
                                class="img-fluid w-100 h-100 bg-secondary rounded" alt="First slide">
                            <a href="#" class="btn px-4 py-2 text-white rounded">{{res.cat_name}}</a>
                        </div>
                    </div>
                </div>
                <h3>List of Categories and Products:</h3>
                <a href="{% url 'admin_app:category_list' %}"><button
                        class="btn btn-primary border-2 border-secondary">Category List</button></a>
                <a href="{% url 'admin_app:p_register' %}"><button class="btn btn-primary border-2 border-secondary">Add
                        Product</button></a>
                <a href="{% url 'admin_app:p_list' %}"><button class="btn btn-primary border-2 border-secondary">Product
                        List</button></a>
            </div>
        </div>
    </div>
</div>
{% endblock hero%}

{% block featurs %}
{% endblock featurs%}

{% block fruits %}
{% endblock fruits %}


{% block featur-2 %}

{% endblock featur-2 %}

{% block vesitable %}

{% endblock vesitable %}

{% block banner %}

{% endblock banner %}

{% block Bestsaler %}

{% endblock Bestsaler %}


{% block testimonial %}

{% endblock testimonial %}

{% block button %}
{% endblock %}

{% block foot %}
{% endblock %}

{% block offer %}
{% endblock %}

{% block footer_tag %}
{% endblock %}

Admin_app/templates/item_delete.html
{% extends "admin_home.html" %}
{% load static %}
{% block model %}
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-center">
                <div class="input-group w-75 mx-auto d-flex">
                    <input type="search" class="form-control p-3" placeholder="keywords"
                        aria-describedby="search-icon-1">
                    <span id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock model %}


{% block hero %}


<div class="container-fluid py-5 mb-5 hero-header">
    <div class="container py-5">
        <div class="row g-5 align-items-center">
            <div class="col-md-12 col-lg-7">
                <h1 class="mb-5 display-3 text-primary">Item Delete</h1>

                <h1>Delete Page</h1>
                <h2>Are you sure to delete record id: {{data.item_id}}<h2>
                        <h3>Name:{{data.item_name}}</h3>
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="position-relative mx-auto">
                                <button type="submit"
                                    class="btn btn-primary border-2 border-secondary py-3 px-4 position-absolute rounded-pill text-white h-60"
                                    style="top: 0; right: 25%;">Delete Product</button>
                            </div>
                        </form>
            </div>
            <div class="col-md-12 col-lg-5">
                <div id="carouselId" class="carousel slide position-relative" data-bs-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active rounded">
                            <img src="{{data.img.url}}" alt="Current Image" width="50" height="50"
                                class="img-fluid w-50 h-75 bg-secondary rounded" alt="First slide">
                        </div>
                    </div>
                </div>
                <h3>List of Categories and Products:</h3>
                <a href="{% url 'admin_app:category_list' %}"><button
                        class="btn btn-primary border-2 border-secondary">Category
                        List</button></a>
                <a href="{% url 'admin_app:p_register' %}"><button class="btn btn-primary border-2 border-secondary">Add
                        Product</button></a>
                <a href="{% url 'admin_app:p_list' %}"><button class="btn btn-primary border-2 border-secondary">Product
                        List</button></a>
            </div>
        </div>
    </div>
</div>
{% endblock hero%}

{% block featurs %}
{% endblock featurs%}

{% block fruits %}
{% endblock fruits %}


{% block featur-2 %}

{% endblock featur-2 %}

{% block vesitable %}

{% endblock vesitable %}

{% block banner %}

{% endblock banner %}

{% block Bestsaler %}

{% endblock Bestsaler %}


{% block testimonial %}

{% endblock testimonial %}

{% block button %}
{% endblock %}

{% block foot %}
{% endblock %}

{% block offer %}
{% endblock %}

{% block footer_tag %}
{% endblock %}


<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="delete">
</form>
</div>
<div><a href="{% url 'admin_app:p_list' %}"><button>Product List</button></a>
</div>

</body>

</html>