Admin_app/urls.py
from django.urls import path
from admin_app.views import *
from django.conf import settings
from django.conf.urls.static import static
app_name = 'admin_app'
urlpatterns = [
    # ----Category----

    path(route='category_register/',
         view=category_register_view, name="category_register"),
    path(route='category_list/', view=category_list_view, name="category_list"),
    path(route='category_update/<int:pk>/',
         view=category_update_view, name="category_update"),
    path(route='category_delete/<int:pk>/',
         view=category_delete_view, name="category_delete"),

    # ----PRODUCT----
    path(route='p_register/', view=item_register_view, name="p_register"),
    path(route='p_list/', view=item_list_view, name="p_list"),
    path(route='p_details/', view=item_details_view, name="p_details"),
    path(route='p_update/<int:pk>/', view=item_update_view, name="p_update"),
    path(route='p_delete/<int:pk>/', view=item_delete_view, name="p_delete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL,
    #   document_root=settings.STATIC_ROOT)

Grocery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Grocery.views import home_view

urlpatterns = [
    path('Admin/', admin.site.urls),
    path(route='customer_app/',
         view=include('customer_app.urls'), name='customer_app'),
    path(route='admin_app/', view=include('admin_app.urls'), name='admin_app'),
    path(route='cart/', view=include('cart.urls'), name='cart'),
    path(route='buy_app/', view=include('buy_app.urls'), name='buy_app'),
    path(route='', view=home_view, name='home_view'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL,
    #   document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from cart.views import cart_view,cart_register,cart_remove

app_name='cart_app'
urlpatterns=[
    path(route='cart_list/',view=cart_view,name='cart_list'),
    path(route='cart_register/<int:p_id>/<int:cust_id>/<str:iname>/<iprice>/',view=cart_register,name='cart_register'),
    path(route='cart_remove/<int:cart_id>/',view=cart_remove,name='cart_remove'),
]

customer_app/urls.py
from django.urls import path
from customer_app.views import *

app_name = 'customer_app'
urlpatterns = [
    path(route='customer_welcome/',
         view=customer_Welcome_view, name='customer_welcome'),
    path(route='customer_register/',
         view=customer_register_view, name='customer_register'),
    path(route='customer_update/',
         view=customer_update_view, name='customer_update'),
    path(route='customer_detail/',
         view=customer_detail_view, name='customer_detail'),
    path(route='customer_list/', view=customer_list_view, name='customer_list'),
    path(route='customer_login/', view=customer_login_view, name='customer_login'),
    path(route='customer_logout/',
         view=customer_logout_view, name='customer_logout'),
    path(route='customer_home/', view=customer_home_view, name='customer_home'),
    path(route='forgot_pwd/', view=forgot_pwd_view, name='forgot_pwd'),
    path(route='customer_otp/<int:pk>/',
         view=customer_otp_view, name='customer_otp'),
    path(route='change_pwd/', view=change_pwd_view, name='change_pwd'),


    path(route='admin_home/', view=admin_home_view, name='admin_home'),
]

Admin_app/models.py
from django.db import models
from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile

# Create your models here.


class category_items(models.Model):
    cat_id = models.AutoField(primary_key=True)
    cat_name = models.CharField(max_length=50)
    cat_img = models.ImageField(upload_to='category/')

    def __str__(self):
        return self.cat_name


class product_item(models.Model):
    cat_id = models.ForeignKey(category_items, on_delete=models.CASCADE)
    item_id = models.AutoField(primary_key=True)
    item_name = models.CharField(max_length=50)
    item_desc = models.TextField()
    item_quantity = models.PositiveIntegerField()
    price = models.FloatField()
    img = models.ImageField(upload_to='items/')

    def __str__(self):
        return self.item_name

    def save(self, *args, **kwargs):
        if self.img:
            # Open the uploaded image
            img = Image.open(self.img)

            # Set the new resolution
            new_width = 500
            new_height = 500
            resized_img = img.resize((new_width, new_height), Image.LANCZOS)

            # Save the resized image back to the model's image field
            buffer = BytesIO()
            resized_img.save(buffer, format='JPEG')  # Change format as needed
            self.img.save(self.img.name, ContentFile(
                buffer.getvalue()), save=False)
        super(product_item, self).save(*args, **kwargs)

Admin_app/forms.py
from typing import Any
from django import forms
from admin_app.models import product_item, category_items
from PIL import Image


def change_resolution(input_image_path, output_image_path, new_width=500, new_height=500):
    # Open the image
    image = Image.open(input_image_path)

    # Resize the image
    resized_image = image.resize((new_width, new_height), Image.LANCZOS)

    # Save the resized image
    resized_image.save(output_image_path)


class category_form(forms.ModelForm):
    class Meta:
        model = category_items
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['Job_role'].widget.attrs.update(
        #     {"rows": "4", "cols": "50"})
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control border-2 border-secondary w-75 py-2 px-4 rounded-pill'
            field.widget.attrs['placeholder'] = "Enter "+str(field.label)


class product_form(forms.ModelForm):
    class Meta:
        model = product_item
        fields = "__all__"
        widgets = {'item_desc': forms.Textarea(
            attrs={"rows": "4", "cols": "50"})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print(self.fields)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control border-2 border-secondary w-75 py-2 px-4 rounded-pill'
            field.widget.attrs['placeholder'] = "Enter "+str(field.label)

Admin_app/views.py
from django.shortcuts import render, redirect
from admin_app.models import category_items, product_item
from admin_app.forms import product_form, category_form
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.

#   ============ CATEGORY Register, List, Update, Delete


def category_register_view(request):
    form = category_form()
    if request.method == 'POST' and request.FILES:
        form = category_form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Category is added.")
        else:
            messages.error(request, "Category is not added.")
    return render(request=request, template_name='category_register.html', context={'form': form})


def category_list_view(request):
    res = category_items.objects.all()
    return render(request=request, template_name='category_list.html', context={'data': res})


def category_update_view(request, pk):
    res = category_items.objects.get(cat_id=pk)
    form = category_form(instance=res)
    if request.method == 'POST' or request.FILES:
        res = category_items.objects.get(cat_id=pk)
        form = category_form(request.POST, request.FILES, instance=res)
        if form.is_valid():
            form.save()
            messages.success(request, "Category is Updated.")
        else:
            messages.error(request, "Category is not Updated.")
    return render(request=request, template_name='category_update.html', context={'data': form, 'res': res})


def category_delete_view(request, pk):
    res = category_items.objects.get(cat_id=pk)
    if request.method == 'POST':
        if category_items.objects.get(cat_id=pk).delete():
            messages.success(request, "Category Deleted")
        else:
            messages.error(request, "Category is not Deleted")
        return redirect('/admin_app/category_list')
    return render(request=request, template_name='category_delete.html', context={'data': res})


#   ============ (item) PRODUCT Register, List, Update, Delete
def item_register_view(request):
    form = product_form()
    if request.method == 'POST' and request.FILES:
        form = product_form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Product added")
        else:
            messages.error(request, "Product is not added")
        return redirect('/admin_app/p_list/')
    return render(request=request, template_name='item_register.html', context={'form': form})


def item_list_view(request):
    category = category_items.objects.all()
    res = product_item.objects.all()
    return render(request=request, template_name='item_list.html', context={'data': res, 'category': category})


def item_details_view(request):
    if request.method == 'POST':
        res = product_item.objects.filter(cat_id=request.POST['cat_list'])
    return render(request=request, template_name='item_list.html', context={'data': res})


def item_update_view(request, pk):
    res = product_item.objects.get(item_id=pk)
    form = product_form(instance=res)
    if request.method == "POST":
        res = product_item.objects.get(item_id=pk)
        form = product_form(request.POST, request.FILES, instance=res)
        if form.is_valid():
            form.save()
            messages.success(request, "Product Updated")
        else:
            messages.error(request, "Product is not Updated")
        return redirect('/admin_app/p_list')
    return render(request=request, template_name='item_update.html', context={'form': form, 'res': res})


def item_delete_view(request, pk):
    res = product_item.objects.get(item_id=pk)
    if request.method == 'POST':
        if product_item.objects.get(item_id=pk).delete():
            messages.success(request, "Product Deleted")
        else:
            messages.error(request, "Product is not deleted")
        return redirect('/admin_app/p_list')
    return render(request=request, template_name='item_delete.html', context={'data': res})

Admin_app/templates/partials/_admin_nav.html
<!-- Navbar start -->

<div class="container-fluid fixed-top">
    <div class="top-link pe-2">
        {% if messages %}
        {% for message in messages %}
        <div class="container-fluid">
            <div class="alert {{message.tags}} alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="container topbar bg-primary d-none d-lg-block">
        <div class="d-flex justify-content-between">
            <div class="top-info ps-2">
                <small class="me-3"><i class="fas fa-map-marker-alt me-2 text-secondary"></i> <a href="#"
                        class="text-white">123 Street, Hyderabad</a></small>
                <small class="me-3"><i class="fas fa-envelope me-2 text-secondary"></i><a href="#"
                        class="text-white">PysGrocery@gmail.com</a></small>
            </div>

            <div class="top-link pe-2">

                <a href="#" class="text-white"><small class="text-white mx-2">{{user}}</small></a>
                {% if user.is_authenticated %}
                <a href="#" class="text-white"><small class="text-white mx-2">{{user.email}}</small>/</a>
                <a href="{% url 'customer_app:customer_logout'%}" class="text-white"><small
                        class="text-white ms-2">Logout</small></a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container px-0">
        <nav class="navbar navbar-light bg-white navbar-expand-xl">
            <a href="index.html" class="navbar-brand">
                <h1 class="text-primary display-6">Online Grocery Management</h1>
            </a>
            <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarCollapse">
                <span class="fa fa-bars text-primary"></span>
            </button>
            <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                <div class="navbar-nav mx-auto">
                    <a href="{% url 'customer_app:customer_home' %}" class="nav-item nav-link active">Home</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                        <div class="dropdown-menu m-0 bg-secondary rounded-0">
                            <a href="{% url 'admin_app:category_register' %}" class="dropdown-item">Category
                                Register</a>
                            <a href="{% url 'admin_app:category_list' %}" class="dropdown-item">Category List</a>
                            <a href="{% url 'admin_app:p_register' %}" class="dropdown-item">Item Register</a>
                            <a href="{% url 'admin_app:p_list' %}" class="dropdown-item">Item List</a>
                        </div>
                    </div>
                    <a href="contact.html" class="nav-item nav-link">Contact</a>
                </div>
                <div class="d-flex m-3 me-0">
                    <button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4"
                        data-bs-toggle="modal" data-bs-target="#searchModal"><i
                            class="fas fa-search text-primary"></i></button>
                    <a href="#" class="position-relative me-4 my-auto">
                        <i class="fa fa-shopping-bag fa-2x"></i>
                        <span
                            class="position-absolute bg-secondary rounded-circle d-flex align-items-center justify-content-center text-dark px-1"
                            style="top: -5px; left: 15px; height: 20px; min-width: 20px;">0</span>
                    </a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Profile</a>
                        <div class="dropdown-menu m-0 bg-secondary rounded-0">
                            <a href="{% url 'customer_app:customer_update'%}" class="dropdown-item">Profile
                                Update</a>
                            <a href="{% url 'customer_app:change_pwd'%}" class="dropdown-item">Change
                                Password</a>
                            <a href="testimonial.html" class="dropdown-item">Orders</a>
                        </div>
                    </div>
                    <a href="{% url 'customer_app:customer_logout'%}" class="my-auto">
                        <i class="fas fa-user fa-2x"></i>
                    </a>
                </div>
            </div>
        </nav>
    </div>
</div>
<!-- Navbar End -->

Admin_app/templates/partials/_footer.html
<!-- Footer Start -->
{% load static %}
<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5">
    <div class="container py-5">
        <div class="pb-4 mb-4" style="border-bottom: 1px solid rgba(226, 175, 24, 0.5) ;">
            <div class="row g-4">
                <div class="col-lg-3">
                    <a href="#">
                        <h1 class="text-primary mb-0">Grocery</h1>
                        <p class="text-secondary mb-0">New products</p>
                    </a>
                </div>
                <div class="col-lg-6">
                    <div class="position-relative mx-auto">
                        <input class="form-control border-0 w-100 py-3 px-4 rounded-pill" type="number"
                            placeholder="Your Email">
                        <button type="submit"
                            class="btn btn-primary border-0 border-secondary py-3 px-4 position-absolute rounded-pill text-white"
                            style="top: 0; right: 0;">Subscribe Now</button>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="d-flex justify-content-end pt-3">
                        <a class="btn  btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i
                                class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i
                                class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i
                                class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-secondary btn-md-square rounded-circle" href=""><i
                                class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <div class="footer-item">
                    <h4 class="text-light mb-3">Why People Like us!</h4>
                    <p class="mb-4">typesetting, remaining essentially unchanged. It was
                        popularised in the 1960s with the like Aldus PageMaker including of Lorem Ipsum.</p>
                    <a href="" class="btn border-secondary py-2 px-4 rounded-pill text-primary">Read More</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="d-flex flex-column text-start footer-item">
                    <h4 class="text-light mb-3">Shop Info</h4>
                    <a class="btn-link" href="">About Us</a>
                    <a class="btn-link" href="">Contact Us</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="d-flex flex-column text-start footer-item">
                    <h4 class="text-light mb-3">Account</h4>
                    <a class="btn-link" href="">My Account</a>
                    <a class="btn-link" href="">Shop details</a>
                    <a class="btn-link" href="">Shopping Cart</a>
                    <a class="btn-link" href="">Wishlist</a>
                    <a class="btn-link" href="">Order History</a>
                    <a class="btn-link" href="">International Orders</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="footer-item">
                    <h4 class="text-light mb-3">Contact</h4>
                    <p>Address: 1234 sheet, Punjagutta, Hyderabad</p>
                    <p>Email: PysGrocery@gmail.com</p>
                    <p>Phone: 99887 74455</p>
                    <p>Payment Accepted</p>
                    <img src="{% static 'img/payment.png' %}" class="img-fluid" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

<!-- Copyright Start -->
<div class="container-fluid copyright bg-dark py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                <span class="text-light"><a href="#"><i class="fas fa-copyright text-light me-2"></i>online Grocery
                        Management</a>, All right reserved.</span>
            </div>
        </div>
    </div>
</div>
</div>
<!-- Copyright End -->

<!-- Back to Top -->
<a href="#" class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i
        class="fa fa-arrow-up"></i></a>

Admin_app/templates/partials/_header.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Fruitables - Vegetable Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    {% load static %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap"
        rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css '}" rel="stylesheet">

</head>

<body>
</body>

</html>

Admin_app/templates/partials/_nav.html
<!-- Navbar start -->



<div class="container-fluid fixed-top">
    <div class="top-link pe-2">
        {% if messages %}
        {% for message in messages %}
        <div class="container-fluid">
            <div class="alert {{message.tags}} alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="container topbar bg-primary d-none d-lg-block">
        <div class="d-flex justify-content-between">
            <div class="top-info ps-2">
                <small class="me-3"><i class="fas fa-map-marker-alt me-2 text-secondary"></i> <a href="#"
                        class="text-white">123 Street, Hyderabad</a></small>
                <small class="me-3"><i class="fas fa-envelope me-2 text-secondary"></i><a href="#"
                        class="text-white">PysGrocery@gmail.com</a></small>
            </div>

            <div class="top-link pe-2">
                <a href="#" class="text-white"><small class="text-white mx-2">Privacy Policy</small>/</a>
                <a href="#" class="text-white"><small class="text-white mx-2">Terms of Use</small>/</a>
                <a href="#" class="text-white"><small class="text-white ms-2">Sales and Refunds</small></a>
            </div>
        </div>
    </div>
    <div class="container px-0">
        <nav class="navbar navbar-light bg-white navbar-expand-xl">
            <a href="index.html" class="navbar-brand">
                <h1 class="text-primary display-6">Online Grocery Management</h1>
            </a>
            <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarCollapse">
                <span class="fa fa-bars text-primary"></span>
            </button>
            <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                <div class="navbar-nav mx-auto">
                    <a href="#" class="nav-item nav-link active">Home</a>
                    <a href="{% url 'admin_app:category_list' %}" class="nav-item nav-link">Shop</a>
                    <a href="shop-detail.html" class="nav-item nav-link">Shop Detail</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                        <div class="dropdown-menu m-0 bg-secondary rounded-0">
                            <a href="cart.html" class="dropdown-item">Cart</a>
                            <a href="chackout.html" class="dropdown-item">Chackout</a>
                            <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                            <a href="404.html" class="dropdown-item">404 Page</a>
                        </div>
                    </div>
                    <a href="contact.html" class="nav-item nav-link">Contact</a>
                </div>
                <div class="d-flex m-3 me-0">
                    <button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4"
                        data-bs-toggle="modal" data-bs-target="#searchModal"><i
                            class="fas fa-search text-primary"></i></button>
                    <a href="#" class="position-relative me-4 my-auto">
                        <i class="fa fa-shopping-bag fa-2x"></i>
                        <span
                            class="position-absolute bg-secondary rounded-circle d-flex align-items-center justify-content-center text-dark px-1"
                            style="top: -5px; left: 15px; height: 20px; min-width: 20px;">0</span>
                    </a>
                    <a href="{% url 'customer_app:customer_welcome'%}" class="my-auto">
                        <i class="fas fa-user fa-2x"></i>
                    </a>
                </div>
            </div>
        </nav>
    </div>
</div>
<!-- Navbar End -->

Admin_app/templates/partials/_spinner.html
<!-- Spinner Start -->
<div id="spinner"
    class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">
    <div class="spinner-grow text-primary" role="status"></div>
</div>
<!-- Spinner End -->