Grocery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Grocery.views import home_view

urlpatterns = [
    path('Admin/', admin.site.urls),
    path(route='customer_app/',
         view=include('customer_app.urls'), name='customer_app'),
    path(route='admin_app/', view=include('admin_app.urls'), name='admin_app'),
    path(route='cart/', view=include('cart.urls'), name='cart'),
    path(route='buy_app/', view=include('buy_app.urls'), name='buy_app'),
    path(route='', view=home_view, name='home_view'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL,
    #   document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from cart.views import cart_view,cart_register,cart_remove

app_name='cart_app'
urlpatterns=[
    path(route='cart_list/',view=cart_view,name='cart_list'),
    path(route='cart_register/<int:p_id>/<int:cust_id>/<str:iname>/<iprice>/',view=cart_register,name='cart_register'),
    path(route='cart_remove/<int:cart_id>/',view=cart_remove,name='cart_remove'),
]

customer_app/urls.py
from django.urls import path
from customer_app.views import *

app_name = 'customer_app'
urlpatterns = [
    path(route='customer_welcome/',
         view=customer_Welcome_view, name='customer_welcome'),
    path(route='customer_register/',
         view=customer_register_view, name='customer_register'),
    path(route='customer_update/',
         view=customer_update_view, name='customer_update'),
    path(route='customer_detail/',
         view=customer_detail_view, name='customer_detail'),
    path(route='customer_list/', view=customer_list_view, name='customer_list'),
    path(route='customer_login/', view=customer_login_view, name='customer_login'),
    path(route='customer_logout/',
         view=customer_logout_view, name='customer_logout'),
    path(route='customer_home/', view=customer_home_view, name='customer_home'),
    path(route='forgot_pwd/', view=forgot_pwd_view, name='forgot_pwd'),
    path(route='customer_otp/<int:pk>/',
         view=customer_otp_view, name='customer_otp'),
    path(route='change_pwd/', view=change_pwd_view, name='change_pwd'),


    path(route='admin_home/', view=admin_home_view, name='admin_home'),
]

customer_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class customer_model(User):
    phone = models.PositiveBigIntegerField(unique=True)
    dob = models.DateField()
    gender = models.CharField(max_length=10,choices=[['Male','Male'],['Female','Female'],['other','other']])
    

customer_app/forms.py
from django import forms
from customer_app.models import customer_model
from django.contrib.auth.hashers import make_password
import re
from customer_app.validators import clean_enter_new_password


class customer_register_form(forms.ModelForm):
    repassword = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = customer_model
        fields = ['username', 'first_name', 'last_name',
                  'email', 'phone', 'gender', 'dob', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print(self.fields)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control border-2 border-secondary w-75 py-2 px-4 rounded-pill'
            field.widget.attrs['placeholder'] = "Enter "+str(field.label)

    def clean_username(self):
        username = self.cleaned_data['username']
        if not (username[0].isupper()):
            raise forms.ValidationError('Username starts with uppercase')
        if len(username) < 3:
            raise forms.ValidationError('Username should be min 3 characters')
        if len(username) > 15:
            raise forms.ValidationError('Username should be max 15 characters')
        return username

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if len(str(phone)) != 10:
            raise forms.ValidationError('Phone number should be 10 digits')
        if str(phone)[0] not in '9876':
            raise forms.ValidationError(
                'Phone numbers start with either 9,8,7,6')
        return phone

    def clean_password(self):
        pwd = self.cleaned_data['password']
        if not (pwd[0].isupper()):
            raise forms.ValidationError('password starts with uppercase')
        if len(pwd) < 3:
            raise forms.ValidationError('password should be min 3 characters')
        if len(pwd) > 15:
            raise forms.ValidationError('password should be max 15 characters')
        if len(re.findall('[0-9]', pwd)) == 0:
            raise forms.ValidationError('password atleast 1 numeric character')
        if len(re.findall('[^0-9a-zA-Z]', pwd)) == 0:
            raise forms.ValidationError('password atleast 1 special character')
        if len(re.findall('[a-z]', pwd)) == 0:
            raise forms.ValidationError(
                'password atleast 1 lowercase character')
        return pwd

    def clean_repassword(self):
        pwd = self.cleaned_data['repassword']
        if not (pwd[0].isupper()):
            raise forms.ValidationError('repassword starts with uppercase')
        if len(pwd) < 3:
            raise forms.ValidationError(
                'repassword should be min 3 characters')
        if len(pwd) > 15:
            raise forms.ValidationError(
                'repassword should be max 15 characters')
        if len(re.findall('[0-9]', pwd)) == 0:
            raise forms.ValidationError(
                'repassword atleast 1 numeric character')
        if len(re.findall('[^0-9a-zA-Z]', pwd)) == 0:
            raise forms.ValidationError(
                'repassword atleast 1 special character')
        if len(re.findall('[a-z]', pwd)) == 0:
            raise forms.ValidationError(
                'repassword atleast 1 lowercase character')
        return pwd

    def save(self, commit=True):
        user = super().save(commit=False)
        if self.cleaned_data['password'] == self.cleaned_data['repassword']:
            user.password = make_password(self.cleaned_data['password'])
            if commit:
                user.save()
            return user


class customer_update_form(forms.ModelForm):
    class Meta:
        model = customer_model
        fields = ['first_name', 'last_name',
                  'email', 'phone', 'gender', 'dob']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print(self.fields)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control border-2 border-secondary w-55 py-2 px-4 rounded-pill'
            field.widget.attrs['placeholder'] = "Enter "+str(field.label)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if len(str(phone)) != 10:
            raise forms.ValidationError('Phone number should be 10 digits')
        if str(phone)[0] not in '9876':
            raise forms.ValidationError(
                'Phone numbers start with either 9,8,7,6')
        return phone


class customer_login_form(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control border-2 border-secondary w-100 py-2 px-4 rounded-pill', 'placeholder': "Username"}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control border-2 border-secondary w-100 py-2 px-4 rounded-pill', 'placeholder': "Password"}))

    def clean_username(self):
        username = self.cleaned_data['username']
        if not (username[0].isupper()):
            raise forms.ValidationError('Username starts with uppercase')
        if len(username) < 3:
            raise forms.ValidationError('Username should be min 3 characters')
        if len(username) > 15:
            raise forms.ValidationError('Username should be max 15 characters')
        return username

    def clean_password(self):
        pwd = self.cleaned_data['password']
        if not (pwd[0].isupper()):
            raise forms.ValidationError('password starts with uppercase')
        if len(pwd) < 3:
            raise forms.ValidationError('password should be min 3 characters')
        if len(pwd) > 15:
            raise forms.ValidationError('password should be max 15 characters')
        if len(re.findall('[0-9]', pwd)) == 0:
            raise forms.ValidationError('password atleast 1 numeric character')
        if len(re.findall('[^0-9a-zA-Z]', pwd)) == 0:
            raise forms.ValidationError('password atleast 1 special character')
        if len(re.findall('[a-z]', pwd)) == 0:
            raise forms.ValidationError(
                'password atleast 1 lowercase character')
        return pwd

    def clean_repassword(self):
        pwd = self.cleaned_data['repassword']
        if not (pwd[0].isupper()):
            raise forms.ValidationError('repassword starts with uppercase')
        if len(pwd) < 3:
            raise forms.ValidationError(
                'repassword should be min 3 characters')
        if len(pwd) > 15:
            raise forms.ValidationError(
                'repassword should be max 15 characters')
        if len(re.findall('[0-9]', pwd)) == 0:
            raise forms.ValidationError(
                'repassword atleast 1 numeric character')
        if len(re.findall('[^0-9a-zA-Z]', pwd)) == 0:
            raise forms.ValidationError(
                'repassword atleast 1 special character')
        if len(re.findall('[a-z]', pwd)) == 0:
            raise forms.ValidationError(
                'repassword atleast 1 lowercase character')
        return pwd


class change_pwd_form(forms.Form):
    enter_new_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control border-2 border-secondary w-100 py-2 px-4 rounded-pill', 'placeholder': "Password"}), validators=[clean_enter_new_password])
    re_enter_password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control border-2 border-secondary w-100 py-2 px-4 rounded-pill', 'placeholder': "RePassword"}))

    def clean_re_enter_password(self):
        password = self.cleaned_data['re_enter_password']
        if not (password[0].isupper()):
            raise forms.ValidationError(
                're entered password starts with uppercase')
        if len(password) < 3:
            raise forms.ValidationError(
                're entered password should be min 3 characters')
        if len(password) > 15:
            raise forms.ValidationError(
                're entered password should be max 15 characters')
        if len(re.findall('[0-9]', password)) == 0:
            raise forms.ValidationError(
                're entered password atleast 1 numeric character')
        if len(re.findall('[^0-9a-zA-Z]', password)) == 0:
            raise forms.ValidationError(
                're entered password atleast 1 special character')
        if len(re.findall('[a-z]', password)) == 0:
            raise forms.ValidationError(
                're entered password atleast 1 lowercase character')
        if self.cleaned_data['enter_new_password'] != password:
            raise forms.ValidationError(
                'New password and re-entered password should be same as password')
        return password

customer_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from admin_app.models import category_items
from customer_app.forms import customer_register_form, customer_login_form, change_pwd_form, customer_update_form
from django.contrib.auth import authenticate, login, logout
from customer_app.models import customer_model
from django.contrib.auth.decorators import login_required
import random
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.hashers import make_password

# Create your views here.


def customer_Welcome_view(request):
    return render(request=request, template_name='base_welcome.html')


def customer_register_view(request):
    form = customer_register_form()
    if request.method == 'POST':
        form = customer_register_form(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Registration Successful.")
            return redirect('/customer_app/customer_login')
        else:
            messages.error(request, "Not Registered.")
    return render(request=request, template_name='customer_register.html', context={'form': form})


def customer_detail_view(request):
    res = customer_model.objects.get(id=request.user.id)
    return render(request=request, template_name='customer_profile.html', context={'form': res})


def customer_update_view(request):
    res = customer_model.objects.get(id=request.user.id)
    form = customer_update_form(instance=res)
    if request.method == 'POST':
        res = customer_model.objects.get(id=request.user.id)
        form = customer_update_form(request.POST, instance=res)
        if form.is_valid():
            form.save()
            messages.success(request, "your details is Updated.")
            return redirect('/customer_app/customer_home')
        else:
            messages.error(request, "your details is not Updated.")
    return render(request=request, template_name='customer_update.html', context={'form': form})


def customer_login_view(request):
    form = customer_login_form()
    if request.method == 'POST':
        form = customer_login_form(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user:
                if user.is_staff:
                    login(request, user)
                    messages.success(request, "Admin Login Successful")
                    return redirect('/customer_app/customer_home')
                elif user.is_active:
                    login(request, user)
                    messages.success(request, "Customer Login Successful")
                    return redirect('/customer_app/customer_home')
                else:
                    messages.Error(request, "Customer Login Failed ")
            else:
                messages.error(request, "username or password is in-correct")
                return redirect('/customer_app/customer_home')

    return render(request=request, template_name='customer_login.html', context={'form': form})


def customer_list_view(request):
    data = customer_model.objects.all()
    return render(request=request, template_name='customer_list.html', context={'data': data})


@login_required(login_url='/customer_app/customer_login')
def customer_home_view(request):
    return render(request=request, template_name='customer_home.html')


def admin_home_view(request):
    return render(request=request, template_name='admin_home.html')


@login_required(login_url='/customer_app/customer_login')
def customer_logout_view(request):
    messages.success(request, "Logout Successful")
    logout(request)
    return redirect('/customer_app/customer_login')


def forgot_pwd_view(request):
    res = customer_model.objects.all().values_list('email')
    global otp_confirm
    if request.method == 'POST':
        otp = random.randint(000000, 999999)
        otp_confirm = otp
        email = request.POST['email']
        if (email,) in res:
            subject = 'Customer verification code'
            msg = f'''Dear customer,
                    Please enter the OTP{otp}
                    Thankyou'''
            send_mail(subject=subject, message=msg,
                      from_email=settings.EMAIL_HOST_USER, recipient_list=[email])
            email_id = customer_model.objects.get(email=email)
            messages.success(request, "Sent OTP to your Register Email.")
            return redirect(f'/customer_app/customer_otp/{email_id.id}/')
        else:
            print("hello")
            messages.error(request, "Email is not register.")
    return render(request=request, template_name='forgot_pwd.html')


def customer_otp_view(request, pk):
    if request.method == 'POST':
        if str(otp_confirm) == str(request.POST['otp']):
            return redirect(f'/customer_app/change_pwd/{pk}/')
        else:
            return redirect('/customer_app/forgot_pwd')
    return render(request=request, template_name='customer_otp.html')


@login_required(login_url='/customer_app/customer_login')
def change_pwd_view(request):
    form = change_pwd_form()
    if request.method == 'POST':
        res = customer_model.objects.get(id=request.user.id)
        form = change_pwd_form(request.POST)
        if form.is_valid():
            if form.cleaned_data['enter_new_password'] == form.cleaned_data['re_enter_password']:
                customer_model.objects.filter(id=request.user.id).update(
                    password=make_password(form.cleaned_data['enter_new_password']))
                messages.success(request, "Password is succesfully changed")
                return redirect('/customer_app/customer_login')
            else:
                messages.warning(
                    request, "Password and repassword should be same")

    return render(request=request, template_name='create_pwd.html', context={'form': form})

customer_app/templates/create_pwd.html
{% extends 'base_welcome.html' %}

{% block title %}
<title>Change Password</title>
{% endblock %}

{% block nav_tag %}
{% include "partials/_authe_nav.html" %}
{% endblock %}

{% block body_title %}
<h4 class="mb-3 display-5 text-primary">Change Password Page</h4>
{% endblock %}

{% block form %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{form}}

    </table>
    <button type="Submit" class="btn btn-primary border-2 border-secondary  rounded-pill text-white h-100"
        style="top: 0; right: 25%;">Change Password</button>
</form>
<hr>
{% endblock %}


{% block button %}
{% endblock %}


{% block foot %}
{% endblock %}

{% block offer %}
{% endblock %}

{% block footer_tag %}
{% include "partials/_authe_footer.html" %}
{% endblock %}

customer_app/templates/customer_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List of Customers</title>
</head>
<body>
    <h1>List of Customers</h1>
    <div>
        {% if data %}
        <table border="5">
            <tr>
                <th>FirstName</th>
                <th>LastName</th>
                <th>UserName</th>
                <th>Email</th>
                <th>Phone</th>
                <th>DOB</th>
            </tr>
            {% for i in data %}
            <tr>
                <td>{{i.FirstName}}</td>
                <td>{{i.LastName}}</td>
                <td>{{i.UserName}}</td>
                <td>{{i.Email}}</td>
                <td>{{i.Phone}}</td>
                <td>{{i.DOB}}</td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <h1>Data is not found</h1>
        {% endif %}
    </div>
    
</body>
</html>

customer_app/templates/customer_login.html
{% extends 'base_welcome.html' %}

{% block title %}
<title>Customer Login</title>
{% endblock %}


{% block body_title %}
<h1 style="text-align: center;">Grocery Login Page</h1>
{% endblock %}

{% block form %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button type="submit" class="btn btn-primary border-2 border-secondary  rounded-pill text-white h-100"
        style="top: 0; right: 25%;">Login</button>
</form>
<a href="{%url 'customer_app:forgot_pwd' %}">forgot password?</a>
{% endblock %}

{% block button %}

{% endblock %}


{% block foot %}
<div class="div3">
    <h4>New User?</h4>
    <a class="login" href="{% url 'customer_app:customer_register' %}"><button
            class="btn btn-secondary border-2 border-primary rounded-pill text-white h-100"
            style="top: 0; right: 25%;">Customer Register</button></a>
</div>
{% endblock %}


</body>

</html>

customer_app/templates/customer_otp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OTP verification</title>
</head>
<body>
    <h3>OTP verification</h3>
    <form action="" method="post">
        {%csrf_token%}
        <table>
            <tr>
                <th>
                    <label for="id_otp">Enter OTP:</label>
                    <input type="number" name="otp" id="id_otp">
                </th>
            </tr>
        </table>
        <input type="submit" value="Verify">
    </form>
</body>
</html>

customer_app/templates/customer_profile.html
{% extends 'base_welcome.html' %}

{% block title %}
<title>Customer Register</title>
{% endblock %}

{% block nav_tag %}
{% include "partials/_authe_nav.html" %}
{% endblock %}


{% block body_title %}
<h1 style="text-align: center;">Customer Profile page</h1>
{% endblock %}

{% block form %}
{% if form %}

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Profile</th>
            <th scope="col">Details</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Username</th>
            <td>{{form.username}}</td>
        </tr>
        <tr>
            <th scope="row">First Name</th>
            <td>{{form.first_name|title}}</td>
        </tr>
        <tr>
            <th scope="row">Last Name</th>
            <td>{{form.last_name|title}}</td>
        </tr>
        <tr>
            <th scope="row">Email</th>
            <td>{{form.email}}</td>
        </tr>
        <tr>
            <th scope="row">Phone</th>
            <td>{{form.phone}}</td>
        </tr>
        <tr>
            <th scope="row">Dob</th>
            <td>{{form.dob}}</td>
        </tr>
        <tr>
            <th scope="row">Gender</th>
            <td>{{form.gender}}</td>
        </tr>
    </tbody>
</table>
{% endif %}
{% endblock %}

{% block button %}
{% endblock %}

{% block foot %}
{% endblock %}

{% block offer %}
{% endblock %}

{% block footer_tag %}
{% include "partials/_authe_footer.html" %}
{% endblock %}

customer_app/templates/customer_register.html
{% extends 'base_welcome.html' %}

{% block title %}
<title>Customer Register</title>
{% endblock %}


{% block body_title %}
<h1 style="text-align: center;">Customer Register</h1>
{% endblock %}

{% block form %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{form}}

    </table>
    <button type="submit" class="btn btn-primary border-2 border-secondary  rounded-pill text-white h-100"
        style="top: 0; right: 25%;">Register</button>
</form>

{% endblock %}

{% block button %}
{% endblock %}

{% block foot %}
<div class="div3    ">
    <h4>Already User?</h4>
    <a class="login" href="{% url 'customer_app:customer_login' %}"><button
            class="btn btn-secondary border-2 border-primary rounded-pill text-white h-100"
            style="top: 0; right: 25%;">Customer or Admin Login</button></a>
    <a href="{%url 'customer_app:forgot_pwd' %}">forgot password?</a>
</div>
{% endblock %}

customer_app/templates/customer_update.html
{% extends 'base_welcome.html' %}

{% block title %}
<title>Customer Register</title>
{% endblock %}

{% block nav_tag %}
{% include "partials/_authe_nav.html" %}
{% endblock %}


{% block body_title %}
<h1 style="text-align: center;">Customer Update page</h1>
{% endblock %}

{% block form %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{form}}

    </table>
    <button type="submit" class="btn btn-primary border-2 border-secondary  rounded-pill text-white h-100"
        style="top: 0; right: 25%;">Update</button>
</form>

{% endblock %}

{% block button %}
{% endblock %}

{% block foot %}
{% endblock %}

{% block offer %}
{% endblock %}

{% block footer_tag %}
{% include "partials/_authe_footer.html" %}
{% endblock %}

customer_app/templates/forgot_pwd.html
{% extends 'base_welcome.html' %}

{% block title %}
<title>Forgot Password</title>
{% endblock %}


{% block body_title %}
<h4 class="mb-3 display-5 text-primary">Forgot Password Page</h4>
{% endblock %}

{% block form %}
<form action="" method="post">
    {% csrf_token %}
    <label for="id_mail">Enter Email:</label>
    <input type="email" name="email" id="id_mail"
        class="form-control border-2 border-secondary w-75 py-3 px-4 rounded-pill" placeholder="Email"><br>
    <button type="Submit" class="btn btn-primary border-2 border-secondary  rounded-pill text-white h-100"
        style="top: 0; right: 25%;">Submit</button>
</form>
<hr>
{% endblock %}


{% block button %}
{% endblock %}

{% block foot %}
<div class="div3">
    <h4>New User? <a class="register" href="{% url 'customer_app:customer_register' %}"><button type="Submit"
                class="btn btn-success border-2 border-secondary  rounded-pill text-white h-100"
                style="top: 0; right: 25%;">Register</button></a></h4>

    <h4>Existing User? <a class="login" href="{% url 'customer_app:customer_login' %}"><button type="Submit"
                class="btn btn-success border-2 border-secondary  rounded-pill text-white h-100"
                style="top: 0; right: 25%;">Login</button></a></h4>
</div>
{% endblock %}